name: Build GoSt
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build GoSt
        run: |
          go mod tidy
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o gost-linux-amd64 .
          sha256sum gost-linux-amd64

      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: gost-linux-amd64
          path: gost-linux-amd64
